### ISSUE TITLE
infitite Processing handshake protocol... 

### ISSUE THREAD

**Issue by Duck1en** [TheSaminator/kriegsspiel-online#1]
Can't play the game, just gets stuck at Processing handshake protocol...

**Comment by TheSaminator** [comment]
I'm going to need more information. What web browser were you using? What web browser was your opponent using? And did the problem persist after refreshing and reconnecting?

**Comment by Duck1en** [comment]
Chrome, my friend is using chrome too
Yea, the problem is still here after refreshing and reconecting
Tried it on the Microsoft Edge too and the problem was still here

**Comment by TheSaminator** [comment]
Alright, I think I fixed it.
